### ISSUE TITLE
Allow baseUrl parameter for .shinybox-overlay

### ISSUE THREAD

**Issue by rolandliwag** [One-com/shinybox#14]
As a mixin, the URLs for some of the background-images get mangled and the only way I can think of to fix this is to set a baseUrl. The default can be '' to maintain backwards compatibility and when importing shinybox.less, the baseUrl can be set as necessary.

**Comment by mwoc** [comment]
When I'm using the version that includes this change, my assetgraph build fails with:

⚠ WARN: http-pub/img/loader.gif: ENOENT, open 'http-pub/img/loader.gif'
         Including assets:
             http-pub/3rdparty/shinybox/shinybox.css
         
 ⚠ WARN: http-pub/img/icons.svg: ENOENT, open 'http-pub/img/icons.svg'
         Including assets:
             http-pub/3rdparty/shinybox/shinybox.css

This is because the URLs used to be location-relative and now are root-relative. 

@rolandliwag is the fix to use the now-configurable path?

**Comment by mwoc** [comment]
If the format could be changed to require people to specify a root-relative path, and default to a path-relative path, that would be non-breaking compared to earlier versions. 
The change in https://github.com/rolandliwag/shinybox/commit/658b1d7b80888f96c2e93a1150f477117c621751 isn't backward compatible I think.

@rolandliwag, @gertsonderby - request for comments :)

**Comment by rolandliwag** [comment]
@mwoc It looks like simply removing the "/" before the relative path should fix this:
``
background: url("@{baseUrl}img/loader.gif") no-repeat center center;
``

I'll submit a pull request.

**Comment by avcs06** [comment]
Fixed in #27
